AllCops:
  TargetRubyVersion: 2.2
  Exclude:
    - 'vendor/**/*'
    - '.chef/**/*'
    - 'local-mode-cache/**/*'
    - 'symboliser-vagrant/**/*'

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 12

Style/NumericLiterals:
  Enabled: false

Metrics/ClassLength:
  Max: 120
