AllCops:
  TargetRubyVersion: 2.1
  Exclude:
    - 'vendor/**/*'
    - '.chef/**/*'
    - 'local-mode-cache/**/*'
    - 'symboliser-vagrant/**/*'

Style/NumericLiterals:
  MinDigits: 6

Style/DoubleNegation:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Style/DateTime:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

Metrics/ClassLength:
  Max: 2000

Metrics/BlockLength:
  Max: 2000

Metrics/AbcSize:
  Max: 20

Metrics/CyclomaticComplexity:
  Max: 9

Metrics/PerceivedComplexity:
  Max: 9

Metrics/ParameterLists:
  Max: 9

Naming/UncommunicativeMethodParamName:
  MinNameLength: 2

Naming/AccessorMethodName:
  Enabled: false
